import dynamic from 'next/dynamic';
import TodoList from '@/components/todolist/TodoLIst';
import { QueryClient, dehydrate, useQuery } from '@tanstack/react-query';
import TutorialService from '../api';
// import TodoPost from '@/components/todopost/TodoPost';
const TodoPost = dynamic(
  () => import('@/components/todopost/TodoPost')
)
import s from './main.module.scss';
import Head from 'next/head';
// const DynamicComponent4 = dynamic(() => import('../components/hello4'))

const Main = () => {

  return (
    <>
      <Head>
        <title>투두 리스트 페이지 샘플</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.main_page}>
        <TodoPost />
        <TodoList />
      </div>
    </>
  )
}

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(['todos'], TutorialService.get);
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
    revalidate: 1,
  };
}

export default Main