import Head from 'next/head';
import Link from 'next/link'

const Url = () => {

  return (
    <>
      <Head>
        <title>메인 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <li>
          <Link href="/todo">
            투두 샘플
          </Link>
        </li>
        <li>
          <Link href="/weather">
            날씨 api
          </Link>
        </li>
        <li>
          <Link href="/recoil">
            recoil test
          </Link>
        </li>
        <li>
          <Link href="/redux">
            redux test
          </Link>
        </li>
      </ul>
    </>
  )
}

export default Url